# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_indiscernibility <- function(input, attr_val) {
    .Call('RoughSets_compute_indiscernibility', PACKAGE = 'RoughSets', input, attr_val)
}

