# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_indiscernibility <- function(input, attr_val, unique_attr_val) {
    .Call(`_RoughSets_compute_indiscernibility`, input, attr_val, unique_attr_val)
}

compute_chaos <- function(input, dec_val, unique_dec_val) {
    .Call(`_RoughSets_compute_chaos`, input, dec_val, unique_dec_val)
}

